---
- name: Setup Python
  import_playbook: ./bootstrap-python/python.yaml

- hosts: remarkable
  user: root

  handlers:
    - name: Restart xochitl
      service:
        name: xochitl
        state: restarted

  tasks:
    - name: Copy Templates
      loop: "{{ templates }}"
      loop_control:
        label: Copying {{ item.name }}
      copy:
        src: "{{ item.src }}"
        dest: /usr/share/remarkable/templates/{{ item.filename }}.png
      notify: Restart xochitl

    - name: Get templates.json
      slurp:
        src: /usr/share/remarkable/templates/templates.json
      register: templates_json

    - name: Modify templates.json
      set_fact:
        templates_json: "{{ templates_json['content'] | b64decode | from_json | combine(lookup('template', 'templates.yaml.j2') | from_yaml, recursive=True, list_merge='append_rp') }}"
    
    - name: Save Pre-Lemur mode
      loop: "{{ lemurs }}"
      loop_control:
        label: Saving {{ item.dest }}
      fetch:
        dest: ./backup/{{ ansible_date_time.iso8601 }}/{{ item.dest }}
        src: /usr/share/remarkable/{{ item.dest }}
    
    - name: Set Lemur mode
      loop: "{{ lemurs }}"
      loop_control:
        label: Copying {{ item.src }}
      copy:
        src: "{{ item.src }}"
        dest: /usr/share/remarkable/{{ item.dest }}
      notify: Restart xochitl

    - name: Write back templates.json
      template:
        src: templates.json.j2
        dest: /usr/share/remarkable/templates/templates.json
      notify: Restart xochitl
